// https://vortex.worldofwarships.eu/api/graphql/glossary/
// 箱子加成翻译
export default {
  4283428784: {
    boostType: 'creditsFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 12,
    custom: {},
    hidden: false,
    id: 4283428784,
    index: 'PCEA011',
    modifiers: { creditsFactor: 1.2 },
    name: 'PCEA011_CRboost_1',
    sortOrder: 1,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '银币+20%'
  },
  4282380208: {
    boostType: 'creditsFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 24,
    custom: {},
    hidden: false,
    id: 4282380208,
    index: 'PCEA012',
    modifiers: { creditsFactor: 1.4 },
    name: 'PCEA012_CRboost_2',
    sortOrder: 2,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '银币+40%'
  },
  4281331632: {
    boostType: 'creditsFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 96,
    custom: {},
    hidden: true,
    id: 4281331632,
    index: 'PCEA013',
    modifiers: { creditsFactor: 2.6 },
    name: 'PCEA013_CRboost_3',
    sortOrder: 3,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '银币+160%'
  },
  4280283056: {
    boostType: 'creditsFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 192,
    custom: {},
    hidden: true,
    id: 4280283056,
    index: 'PCEA014',
    modifiers: { creditsFactor: 4.2 },
    name: 'PCEA014_CRboost_4',
    sortOrder: 4,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '银币+320%'
  },
  4272943024: {
    boostType: 'expFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 12,
    custom: {},
    hidden: false,
    id: 4272943024,
    index: 'PCEA021',
    modifiers: { expFactor: 2.0 },
    name: 'PCEA021_TotalXPboost_1',
    sortOrder: 1,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '战舰经验+100%'
  },
  4271894448: {
    boostType: 'expFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 24,
    custom: {},
    hidden: false,
    id: 4271894448,
    index: 'PCEA022',
    modifiers: { expFactor: 3.0 },
    name: 'PCEA022_TotalXPboost_2',
    sortOrder: 2,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '战舰经验+200%'
  },
  4270845872: {
    boostType: 'expFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 96,
    custom: {},
    hidden: true,
    id: 4270845872,
    index: 'PCEA023',
    modifiers: { expFactor: 9.0 },
    name: 'PCEA023_TotalXPboost_3',
    sortOrder: 3,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '战舰经验+800%'
  },
  4269797296: {
    boostType: 'expFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 192,
    custom: {},
    hidden: true,
    id: 4269797296,
    index: 'PCEA024',
    modifiers: { expFactor: 17.0 },
    name: 'PCEA024_TotalXPboost_4',
    sortOrder: 4,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '战舰经验+1600%'
  },
  4262457264: {
    boostType: 'crewExpFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 12,
    custom: {},
    hidden: false,
    id: 4262457264,
    index: 'PCEA031',
    modifiers: { crewExpFactor: 2.0 },
    name: 'PCEA031_CrewXPboost_1',
    sortOrder: 1,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '指挥官经验+100%'
  },
  4261408688: {
    boostType: 'crewExpFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 24,
    custom: {},
    hidden: false,
    id: 4261408688,
    index: 'PCEA032',
    modifiers: { crewExpFactor: 3.0 },
    name: 'PCEA032_CrewXPboost_2',
    sortOrder: 2,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '指挥官经验+200%'
  },
  4260360112: {
    boostType: 'crewExpFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 96,
    custom: {},
    hidden: true,
    id: 4260360112,
    index: 'PCEA033',
    modifiers: { crewExpFactor: 9.0 },
    name: 'PCEA033_CrewXPboost_3',
    sortOrder: 3,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '指挥官经验+800%'
  },
  4259311536: {
    boostType: 'crewExpFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 192,
    custom: {},
    hidden: true,
    id: 4259311536,
    index: 'PCEA034',
    modifiers: { crewExpFactor: 17.0 },
    name: 'PCEA034_CrewXPboost_4',
    sortOrder: 4,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '指挥官经验+1600%'
  },
  4251971504: {
    boostType: 'freeExpFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 12,
    custom: {},
    hidden: false,
    id: 4251971504,
    index: 'PCEA041',
    modifiers: { freeExpFactor: 4.0 },
    name: 'PCEA041_FreeXPboost_1',
    sortOrder: 1,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '全局经验+300%'
  },
  4250922928: {
    boostType: 'freeExpFactor',
    canBuy: true,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 24,
    custom: {},
    hidden: false,
    id: 4250922928,
    index: 'PCEA042',
    modifiers: { freeExpFactor: 7.0 },
    name: 'PCEA042_FreeXPboost_2',
    sortOrder: 2,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '全局经验+600%'
  },
  4249874352: {
    boostType: 'freeExpFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 96,
    custom: {},
    hidden: true,
    id: 4249874352,
    index: 'PCEA043',
    modifiers: { freeExpFactor: 25.0 },
    name: 'PCEA043_FreeXPboost_3',
    sortOrder: 3,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '全局经验+2400%'
  },
  4248825776: {
    boostType: 'freeExpFactor',
    canBuy: false,
    canCharge: true,
    canSell: true,
    costCR: -1,
    costGold: 288,
    custom: {},
    hidden: true,
    id: 4248825776,
    index: 'PCEA044',
    modifiers: { freeExpFactor: 73.0 },
    name: 'PCEA044_FreeXPboost_4',
    sortOrder: 4,
    tags: [],
    typeinfo: {
      nation: 'Common',
      species: 'Camoboost',
      type: 'Exterior'
    },
    title: '全局经验+7200%'
  }
}
